// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/13/2024, 2:32:02 PM
const configMerger = require("/Users/josecaceres/Code/proyectos/hidrogeno-verde/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/josecaceres/Code/proyectos/hidrogeno-verde/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/josecaceres/Code/proyectos/hidrogeno-verde/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/josecaceres/Code/proyectos/hidrogeno-verde/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/josecaceres/Code/proyectos/hidrogeno-verde/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/josecaceres/Code/proyectos/hidrogeno-verde/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/josecaceres/Code/proyectos/hidrogeno-verde/plugins/**/*.{js,ts,mjs}","/Users/josecaceres/Code/proyectos/hidrogeno-verde/composables/**/*.{js,ts,mjs}","/Users/josecaceres/Code/proyectos/hidrogeno-verde/utils/**/*.{js,ts,mjs}","/Users/josecaceres/Code/proyectos/hidrogeno-verde/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/josecaceres/Code/proyectos/hidrogeno-verde/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/josecaceres/Code/proyectos/hidrogeno-verde/app.config.{js,ts,mjs}"] } }));

module.exports = config
