// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 13/12/2024, 13:25:41
const configMerger = require("C:/Users/jlclo/Escritorio/Code/proyectos/hidrogeno-verde/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/jlclo/Escritorio/Code/proyectos/hidrogeno-verde/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jlclo/Escritorio/Code/proyectos/hidrogeno-verde/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jlclo/Escritorio/Code/proyectos/hidrogeno-verde/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jlclo/Escritorio/Code/proyectos/hidrogeno-verde/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jlclo/Escritorio/Code/proyectos/hidrogeno-verde/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jlclo/Escritorio/Code/proyectos/hidrogeno-verde/plugins/**/*.{js,ts,mjs}","C:/Users/jlclo/Escritorio/Code/proyectos/hidrogeno-verde/composables/**/*.{js,ts,mjs}","C:/Users/jlclo/Escritorio/Code/proyectos/hidrogeno-verde/utils/**/*.{js,ts,mjs}","C:/Users/jlclo/Escritorio/Code/proyectos/hidrogeno-verde/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jlclo/Escritorio/Code/proyectos/hidrogeno-verde/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/jlclo/Escritorio/Code/proyectos/hidrogeno-verde/app.config.{js,ts,mjs}"] } }));

module.exports = config
